import manifest from "@/data/asset-manifest.json";

/**
 * Real assets actually present under /public (generated by scripts/gen-assets.mjs
 * at prebuild). Lets components render a real photo when the file exists and a
 * branded placeholder when it doesn't — without ever fetching images off the web.
 */
const ASSETS = new Set(manifest as string[]);

/** True when a real image file exists at this /public path. */
export function hasAsset(path?: string | null): boolean {
  return !!path && ASSETS.has(path);
}

/** Returns the path only if the real file exists, else undefined. */
export function realOrNone(path?: string | null): string | undefined {
  return hasAsset(path) ? (path as string) : undefined;
}
